sudo: required
language: cpp
services:
  - docker
compiler:
  - gcc
before_install:
  - docker pull claria/cvmfs-cms
  - printenv
script:
  - docker run --privileged -e TRAVIS_BRANCH="${TRAVIS_BRANCH}" -e TRAVIS_COMMIT="${TRAVIS_COMMIT}" -v ${TRAVIS_BUILD_DIR}:/home/travis claria/cvmfs-cms /bin/bash -c "cd /home/; /home/travis/test_build.sh"
